default: all

# all: simpleTerm newSimpleTerm basicTerm gnuTerm
all:yash

clean:
	# rm -f simpleTerm
	# rm -f newSimpleTerm
	# rm -f basicTerm
	# rm -f gnuTerm
	rm -f yash
	# rm -f *.txt

yash: client.c
	gcc -o yash client.c -lreadline 
